apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: blue
  template:
    metadata:
      labels:
        app: myapp
        version: blue
    spec:
      containers:
      - name: nginx-blue
        image: devopswithcloudhub/nginx:blue

--- 
apiVersion: v1
kind: Service
metadata: 
  name: myapp-svc
spec:
  selector: 
    app: myapp
    version: blue
  ports:
  - port: 80
    targetPort: 80
  type: NodePort