apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }} #nginx-deploy
spec:
  replicas: {{ .Values.replicas.default }}
  selector:
    matchLabels:
      app: myapp
      version: blue
  template:
    metadata:
      labels:
        app: myapp
        version: blue
    spec:
      containers:
      - name: nginx-blue
        image: {{ .Values.image.name}}:{{ .Values.image.tag}}
        ports:
        - containerPort: 80